### ISSUE TITLE
Send a transaction using quais in the snap

### ISSUE THREAD

**Issue by DenisIvanov26** [dominant-strategies/quai-snap#104]
- Create a quais provider instead of an ethers
- Connect to the correct rpc endpoint (Ex: https://garden.cyprus3.rpc.quaiscan.io/)
- Send a tx

**Comment by skunal8197** [comment]
Finished all 3, but ran into an error when sending a tx 


Payload: https://github.com/dominant-strategies/quai-snap/blob/usingQuais/index.html#L467-L475
Error:
`(unknown) Problem found: Error: unsupported transaction type: undefined (operation="serializeTransaction", transactionType=undefined, code=UNSUPPORTED_OPERATION, version=transactions/5.7.0)
`

**Comment by alanorwick** [comment]
@skunal8197 is this still relevant in the `usingQuais` branch?

**Comment by skunal8197** [comment]
> @skunal8197 is this still relevant in the `usingQuais` branch?

Yes, this is currently being worked on

**Comment by skunal8197** [comment]
internal tx and external tx can be sent
