### ISSUE TITLE
added accounts disappear after metamask disable and re-enable

### ISSUE THREAD

**Issue by hubchub** [dominant-strategies/quai-snap#142]
accounts should persist in meta mask

@DenisIvanov26 discovered this error on 03/15/2023 on version 0.3.0-rc.0

@hubchub could not reproduce the error on 0.2.0-rc.1
upgrading to 0.3.0-rc.0 reproduced the error
downgrading back to 0.2.0-rc.1 did not make the error go away

we need to track down the root of this and get it fixed

otherwise users wont be able to sign in the same meta mask and access the same quai accounts on two different machines

**Comment by skunal8197** [comment]
This only happens when a new account is added to the original set of 13 accounts.

**Comment by skunal8197** [comment]
I am unable to reproduce this on branch `progress380` which is part of [PR 400](https://github.com/dominant-strategies/quai-dashboard/pull/400) running on version 0.15.0-pre.17 of the dashboard

**Comment by skunal8197** [comment]
I still wasn't able to reproduce but got a different problem on Firefox. The same account (with same address and account name) is being generated

![image](https://user-images.githubusercontent.com/12708726/226461474-e5b32451-b8de-4ff3-8965-870b976f81d5.png)

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
Version: 0.15.0-pre.17
Branch: progress380
