### ISSUE TITLE
Update quai-snap address range and remove Prime and Regions

### ISSUE THREAD

**Issue by hendrymason** [dominant-strategies/quai-snap#156]
- [x] Remove prime/region shards from `shardsToFind`
- [x] Update tests

**Comment by skunal8197** [comment]
tracking
https://github.com/MetaMask/snaps-monorepo/issues/1367

**Comment by skunal8197** [comment]
> Blocked by #1367 in snaps-monorepo

Still partially blocked by MetaMask. The PR was merged, but there has not been a new release cut. 

A patch was made on snaps CLI here to enable further local testing for the wallet
https://github.com/dominant-strategies/quai-snap/tree/patchingMetaMaskBabelIssue

**Comment by skunal8197** [comment]
Fixed tests with local patch snaps CLI  
https://github.com/dominant-strategies/quai-snap/commit/6e6793f9e8a53d6b57f53d1e6344a93788bbe7a0
